apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.tenant }} 
  name: {{ .Values.tenant }}-service-external-ingress
  annotations:
    {{- if eq .Values.enableGateway "true" }}
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
    konghq.com/plugins: rate-limiting-by-ip
    {{- else }}
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.host }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/group.name: {{ .Values.tenant }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.referenceApplication.healthCheckPath }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '{{ .Values.referenceApplication.healthCheckInterval }}'
    {{- end }}
    centralsquare.com/external-dns-instance: external
  labels:
    app.kubernetes.io/name: "{{ .Values.tenant }}-service-external-ingress"
    app.kubernetes.io/instance:  "{{ .Values.tenant }}"
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: "{{ .Values.referenceApplication.serviceName }}" 
    app.kubernetes.io/part-of: "{{ .Values.tenant }}"
    app.kubernetes.io/managed-by: "helm"
    app.kubernetes.io/created-by: "helm"  
spec:
  rules: 
  {{- if eq .Values.enableGateway "true" }}
    - host: "{{ .Values.gateway }}"      
      http:
        paths:
         - path: /{{ .Values.tenant }}/api/*
           pathType: ImplementationSpecific
  {{- else}}
    - host: "{{ .Values.host }}"      
      http:
        paths:
         - path: /*
           backend:
             serviceName: ssl-redirect
             servicePort: use-annotation
         - path: /*
  {{- end }}
           backend:
             serviceName: {{ .Values.referenceApplication.serviceName }}-service
             servicePort: {{ .Values.referenceApplication.servicePort }}